name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.6"

      - name: Build Windows Wheel
        run: |
          pip install "setuptools<=59.6.0" wheel build
          python -m build --wheel --no-isolation.

      - name: Build Windows Wheel
        run: python setup.py bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
