name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build Windows x64 Wheel
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.6"

    - name: Install build tools
      run: |
        # Upgrade pip to the last version that supported 3.6
        python -m pip install --upgrade "pip<22.0"
        # Manually install the specific versions you need
        python -m pip install "setuptools<=59.6.0" "wheel" "build"
        
    - name: Build Windows Wheel
      run: python -m build --wheel --no-isolation

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
